package tw.org.narl.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(af3cf9c6fa8ea86dbe827553db4be135)
 */
@org.kie.api.definition.type.Label(value = "\u7C3D\u6838\u4EBA")
public class Approver  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "\u89D2\u8272ID")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String roleId;

    public Approver() {
    }

    public Approver(java.lang.String roleId) {
        this.roleId = roleId;
    }


    
    public java.lang.String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(java.lang.String roleId) {
        this.roleId = roleId;
    }
}