package tw.org.narl.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(f02a44753d7a4e7d185e31fff01eb6f9)
 */
@org.kie.api.definition.type.Label(value = "\u8868\u55AE")
public class Form extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "\u7533\u8ACB\u4EBA\u89D2\u8272")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.String applicanRole;
    
    @org.kie.api.definition.type.Label(value = "\u7533\u8ACB\u8005ID")
    @org.kie.api.definition.type.Position(value = 10)
    private java.lang.String applicantId;
    
    @org.kie.api.definition.type.Label(value = "\u7533\u8ACB\u4EBA\u59D3\u540D")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String applicantName;
    
    @org.kie.api.definition.type.Label(value = "\u7533\u8ACB\u4EBARole(\u6C7A\u7528)")
    @org.kie.api.definition.type.Position(value = 13)
    private java.lang.String applyRole;
    
    @org.kie.api.definition.type.Label(value = "\u76F4\u5C6C\u4E3B\u7BA1RoleLevel")
    @org.kie.api.definition.type.Position(value = 29)
    private java.lang.String bossRoleLevel;
    
    @org.kie.api.definition.type.Label(value = "\u4E2D\u5FC3\u540D\u7A31")
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.String center;
    
    @org.kie.api.definition.type.Label(value = "\u4E2D\u5FC3ID")
    @org.kie.api.definition.type.Position(value = 12)
    private java.lang.String centerId;
    
    @org.kie.api.definition.type.Label(value = "ABC\u4FEE\u6539\u4EBA\u59D3\u540D")
    @org.kie.api.definition.type.Position(value = 32)
    private java.lang.String changeAbcName;
    
    @org.kie.api.definition.type.Label(value = "\u81EA\u9078\u6703\u6838\u55AE\u4F4D3")
    @org.kie.api.definition.type.Position(value = 21)
    private java.lang.String countersignId3;
    
    @org.kie.api.definition.type.Label(value = "\u81EA\u9078\u6703\u6838\u55AE\u4F4D4")
    @org.kie.api.definition.type.Position(value = 22)
    private java.lang.String countersignId4;
    
    @org.kie.api.definition.type.Label(value = "\u81EA\u9078\u6703\u6838\u55AE\u4F4D5")
    @org.kie.api.definition.type.Position(value = 23)
    private java.lang.String countersignId5;
    
    @org.kie.api.definition.type.Label(value = "\u81EA\u9078\u6703\u6838\u55AE\u4F4D6")
    @org.kie.api.definition.type.Position(value = 25)
    private java.lang.String countersignId6;
    
    @org.kie.api.definition.type.Label(value = "\u81EA\u9078\u6703\u6838\u55AE\u4F4D7")
    @org.kie.api.definition.type.Position(value = 27)
    private java.lang.String countersignId7;
    
    @org.kie.api.definition.type.Label(value = "\u81EA\u9078\u6703\u6838\u55AE\u4F4D8")
    @org.kie.api.definition.type.Position(value = 28)
    private java.lang.String countersignId8;
    
    @org.kie.api.definition.type.Label(value = "\u6703\u7C3D\u4EBA1")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String countersignid1;
    
    @org.kie.api.definition.type.Label(value = "\u6703\u7C3D\u4EBA2")
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.String countersignid2;
    
    @org.kie.api.definition.type.Label(value = "\u586B\u55AE\u4EBA")
    @org.kie.api.definition.type.Position(value = 24)
    private java.lang.String creatorId;
    
    @org.kie.api.definition.type.Label(value = "\u76EE\u524D\u95DC\u5361")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String currentStage;
    
    @org.kie.api.definition.type.Label(value = "\u4F01\u63A8\u7D44\u7D44\u9577")
    @org.kie.api.definition.type.Position(value = 52)
    private java.lang.String dh;
    
    @org.kie.api.definition.type.Label(value = "\u9662\u672C\u90E8\u4F01\u8003\u5BA4\u4E3B\u4EFB")
    @org.kie.api.definition.type.Position(value = 53)
    private java.lang.String director_01020000;
    
    @org.kie.api.definition.type.Label(value = "\u8CA1\u52D9\u6703\u8A08\u5BA4\u4E3B\u4EFB")
    @org.kie.api.definition.type.Position(value = 55)
    private java.lang.String director_01110000;
    
    @org.kie.api.definition.type.Label(value = "\u884C\u653F\u670D\u52D9\u5BA4\u4E3B\u4EFB")
    @org.kie.api.definition.type.Position(value = 50)
    private java.lang.String director_01140000;
    
    @org.kie.api.definition.type.Label(value = "\u4E3B\u4EFB")
    @org.kie.api.definition.type.Position(value = 47)
    private java.lang.String director_02010000;
    
    @org.kie.api.definition.type.Label(value = "\u8ACB\u8CFC\u55AE\u7DE8\u865F")
    @org.kie.api.definition.type.Position(value = 18)
    private java.lang.String erpNo;
    
    @org.kie.api.definition.type.Label(value = "erpAdaptor\u50B3\u56DE\u4E4B\u932F\u8AA4\u8A0A\u606F")
    @org.kie.api.definition.type.Position(value = 11)
    private java.lang.String errorMessage;
    
    @org.kie.api.definition.type.Label(value = "\u9662\u99D0\u9EDE\u9810\u63A7\u4EBA\u54E1")
    @org.kie.api.definition.type.Position(value = 42)
    private java.lang.String fbcRoleId;
    
    @org.kie.api.definition.type.Label(value = "\u9662\u90E8\u99D0\u9EDE\u6703\u8A08\u4EBA\u54E1")
    @org.kie.api.definition.type.Position(value = 44)
    private java.lang.String finRoleId;
    
    @org.kie.api.definition.type.Label(value = "\u9662\u99D0\u9EDE\u6703\u8A08\u4E3B\u7BA1")
    @org.kie.api.definition.type.Position(value = 54)
    private java.lang.String fin_mgr;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String formId;
    
    @org.kie.api.definition.type.Label(value = "\u7533\u8ACB\u55AE\u7DE8\u865F")
    @org.kie.api.definition.type.Position(value = 30)
    private java.lang.String formNo;
    
    @org.kie.api.definition.type.Label(value = "ABC\u662F\u5426\u88AB\u4FEE\u6539")
    @org.kie.api.definition.type.Position(value = 34)
    private java.lang.String isAbc;
    
    @org.kie.api.definition.type.Label(value = "\u532F\u5165\u532F\u5165erp\u662F\u5426\u6210\u529F")
    @org.kie.api.definition.type.Position(value = 16)
    private java.lang.String isSuccess;
    
    @org.kie.api.definition.type.Label(value = "\u6CD5\u52D9\u4EBA\u54E1")
    @org.kie.api.definition.type.Position(value = 51)
    private java.lang.String ls;
    
    @org.kie.api.definition.type.Label(value = "\u6D41\u7A0BID")
    @org.kie.api.definition.type.Position(value = 20)
    private java.lang.String mid;
    
    @org.kie.api.definition.type.Label(value = "\u7E3D\u91D1\u984D")
    @org.kie.api.definition.type.Position(value = 26)
    private java.lang.Integer netValue;
    
    @org.kie.api.definition.type.Label(value = "\u4F01\u8003\u4EBA\u54E1")
    @org.kie.api.definition.type.Position(value = 41)
    private java.lang.String peRoleId;
    
    @org.kie.api.definition.type.Label(value = "\u8A08\u756B\u4EE3\u78BC")
    @org.kie.api.definition.type.Position(value = 14)
    private java.lang.String planId;
    
    @org.kie.api.definition.type.Label(value = "\u6574\u5408\u578B\u8A08\u756B\u4E3B\u6301\u4EBA")
    @org.kie.api.definition.type.Position(value = 37)
    private java.lang.String planMgrId;
    
    @org.kie.api.definition.type.Label(value = "\u8A08\u756B\u7D44\u54E1\u89D2\u8272")
    @org.kie.api.definition.type.Position(value = 31)
    private java.lang.String planRole;
    
    @org.kie.api.definition.type.Label(value = "\u9662\u99D0\u9EDE\u4E2D\u5FC3\u63A1\u8CFC")
    @org.kie.api.definition.type.Position(value = 39)
    private java.lang.String poRoleId;
    
    @org.kie.api.definition.type.Label(value = "\u9662\u99D0\u9EDE\u884C\u653F\u7D44\u9577")
    @org.kie.api.definition.type.Position(value = 49)
    private java.lang.String po_mgr;
    
    @org.kie.api.definition.type.Label(value = "\u570B\u7814\u9662\u9662\u9577")
    @org.kie.api.definition.type.Position(value = 56)
    private java.lang.String president;
    
    @org.kie.api.definition.type.Label(value = "\u91D1\u984D")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Long price;
    
    @org.kie.api.definition.type.Label(value = "\u7D00\u9304\u7A0B\u5F0F\u6D41\u7A0B")
    @org.kie.api.definition.type.Position(value = 33)
    private java.lang.String processName;
    
    @org.kie.api.definition.type.Label(value = "\u8CFC\u6848\u6027\u8CEA")
    @org.kie.api.definition.type.Position(value = 43)
    private java.lang.String purchassProp;
    
    @org.kie.api.definition.type.Label(value = "\u4EE3\u767C\u6587\u8005")
    @org.kie.api.definition.type.Position(value = 36)
    private java.lang.String replaceId;
    
    @org.kie.api.definition.type.Label(value = "\u6D41\u7A0B\u7D50\u679C")
    @org.kie.api.definition.type.Position(value = 15)
    private java.lang.String result;
    
    @org.kie.api.definition.type.Label(value = "\u7D93\u8CBB\u4F86\u6E90")
    @org.kie.api.definition.type.Position(value = 38)
    private java.lang.String soureId;
    
    @org.kie.api.definition.type.Label(value = "\u8CA1\u7522\u7BA1\u7406\u54E1")
    @org.kie.api.definition.type.Position(value = 48)
    private java.lang.String staff_pa;
    
    @org.kie.api.definition.type.Label(value = "\u95DC\u5361\u8868")
    @org.kie.api.definition.type.Position(value = 3)
    private java.util.List<tw.org.narl.common.model.Stage> stageList;
    
    @org.kie.api.definition.type.Label(value = "\u7C3D\u6838\u72C0\u614B")
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String status;
    
    @org.kie.api.definition.type.Label(value = "\u6458\u8981")
    @org.kie.api.definition.type.Position(value = 35)
    private java.lang.String summary;
    
    @org.kie.api.definition.type.Label(value = "\u901F\u5225")
    @org.kie.api.definition.type.Position(value = 17)
    private java.lang.Integer timeLimit;
    
    @org.kie.api.definition.type.Label(value = "\u526F\u4E3B\u4EFB")
    @org.kie.api.definition.type.Position(value = 46)
    private java.lang.String vd_02010000;
    
    @org.kie.api.definition.type.Label(value = "\u5948\u7C73\u526F\u4E3B\u4EFB_New")
    @org.kie.api.definition.type.Position(value = 45)
    private java.lang.String vdcRoleId;
    
    @org.kie.api.definition.type.Label(value = "\u526F\u4E3B\u4EFB/\u9662\u9577ID")
    @org.kie.api.definition.type.Position(value = 19)
    private java.lang.String viceManagerId;
    
    @org.kie.api.definition.type.Label(value = "\u662F\u5426\u70BA\u798F\u59D4\u6703")
    @org.kie.api.definition.type.Position(value = 40)
    private java.lang.String welfare;

    public Form() {
    }

    public Form(java.lang.String formId, java.lang.Long price, java.lang.String applicantName, java.util.List<tw.org.narl.common.model.Stage> stageList, java.lang.String currentStage, java.lang.String countersignid1, java.lang.String applicanRole, java.lang.String status, java.lang.String countersignid2, java.lang.String center, java.lang.String applicantId, java.lang.String errorMessage, java.lang.String centerId, java.lang.String applyRole, java.lang.String planId, java.lang.String result, java.lang.String isSuccess, java.lang.Integer timeLimit, java.lang.String erpNo, java.lang.String viceManagerId, java.lang.String mid, java.lang.String countersignId3, java.lang.String countersignId4, java.lang.String countersignId5, java.lang.String creatorId, java.lang.String countersignId6, java.lang.Integer netValue, java.lang.String countersignId7, java.lang.String countersignId8, java.lang.String bossRoleLevel, java.lang.String formNo, java.lang.String planRole, java.lang.String changeAbcName, java.lang.String processName, java.lang.String isAbc, java.lang.String summary, java.lang.String replaceId, java.lang.String planMgrId, java.lang.String soureId, java.lang.String poRoleId, java.lang.String welfare, java.lang.String peRoleId, java.lang.String fbcRoleId, java.lang.String purchassProp, java.lang.String finRoleId, java.lang.String vdcRoleId, java.lang.String vd_02010000, java.lang.String director_02010000, java.lang.String staff_pa, java.lang.String po_mgr, java.lang.String director_01140000, java.lang.String ls, java.lang.String dh, java.lang.String director_01020000, java.lang.String fin_mgr, java.lang.String director_01110000, java.lang.String president) {
        this.formId = formId;
        this.price = price;
        this.applicantName = applicantName;
        this.stageList = stageList;
        this.currentStage = currentStage;
        this.countersignid1 = countersignid1;
        this.applicanRole = applicanRole;
        this.status = status;
        this.countersignid2 = countersignid2;
        this.center = center;
        this.applicantId = applicantId;
        this.errorMessage = errorMessage;
        this.centerId = centerId;
        this.applyRole = applyRole;
        this.planId = planId;
        this.result = result;
        this.isSuccess = isSuccess;
        this.timeLimit = timeLimit;
        this.erpNo = erpNo;
        this.viceManagerId = viceManagerId;
        this.mid = mid;
        this.countersignId3 = countersignId3;
        this.countersignId4 = countersignId4;
        this.countersignId5 = countersignId5;
        this.creatorId = creatorId;
        this.countersignId6 = countersignId6;
        this.netValue = netValue;
        this.countersignId7 = countersignId7;
        this.countersignId8 = countersignId8;
        this.bossRoleLevel = bossRoleLevel;
        this.formNo = formNo;
        this.planRole = planRole;
        this.changeAbcName = changeAbcName;
        this.processName = processName;
        this.isAbc = isAbc;
        this.summary = summary;
        this.replaceId = replaceId;
        this.planMgrId = planMgrId;
        this.soureId = soureId;
        this.poRoleId = poRoleId;
        this.welfare = welfare;
        this.peRoleId = peRoleId;
        this.fbcRoleId = fbcRoleId;
        this.purchassProp = purchassProp;
        this.finRoleId = finRoleId;
        this.vdcRoleId = vdcRoleId;
        this.vd_02010000 = vd_02010000;
        this.director_02010000 = director_02010000;
        this.staff_pa = staff_pa;
        this.po_mgr = po_mgr;
        this.director_01140000 = director_01140000;
        this.ls = ls;
        this.dh = dh;
        this.director_01020000 = director_01020000;
        this.fin_mgr = fin_mgr;
        this.director_01110000 = director_01110000;
        this.president = president;
    }


    
    public java.lang.String getApplicanRole() {
        return this.applicanRole;
    }

    public void setApplicanRole(java.lang.String applicanRole) {
        this.applicanRole = applicanRole;
    }
    
    public java.lang.String getApplicantId() {
        return this.applicantId;
    }

    public void setApplicantId(java.lang.String applicantId) {
        this.applicantId = applicantId;
    }
    
    public java.lang.String getApplicantName() {
        return this.applicantName;
    }

    public void setApplicantName(java.lang.String applicantName) {
        this.applicantName = applicantName;
    }
    
    public java.lang.String getApplyRole() {
        return this.applyRole;
    }

    public void setApplyRole(java.lang.String applyRole) {
        this.applyRole = applyRole;
    }
    
    public java.lang.String getBossRoleLevel() {
        return this.bossRoleLevel;
    }

    public void setBossRoleLevel(java.lang.String bossRoleLevel) {
        this.bossRoleLevel = bossRoleLevel;
    }
    
    public java.lang.String getCenter() {
        return this.center;
    }

    public void setCenter(java.lang.String center) {
        this.center = center;
    }
    
    public java.lang.String getCenterId() {
        return this.centerId;
    }

    public void setCenterId(java.lang.String centerId) {
        this.centerId = centerId;
    }
    
    public java.lang.String getChangeAbcName() {
        return this.changeAbcName;
    }

    public void setChangeAbcName(java.lang.String changeAbcName) {
        this.changeAbcName = changeAbcName;
    }
    
    public java.lang.String getCountersignId3() {
        return this.countersignId3;
    }

    public void setCountersignId3(java.lang.String countersignId3) {
        this.countersignId3 = countersignId3;
    }
    
    public java.lang.String getCountersignId4() {
        return this.countersignId4;
    }

    public void setCountersignId4(java.lang.String countersignId4) {
        this.countersignId4 = countersignId4;
    }
    
    public java.lang.String getCountersignId5() {
        return this.countersignId5;
    }

    public void setCountersignId5(java.lang.String countersignId5) {
        this.countersignId5 = countersignId5;
    }
    
    public java.lang.String getCountersignId6() {
        return this.countersignId6;
    }

    public void setCountersignId6(java.lang.String countersignId6) {
        this.countersignId6 = countersignId6;
    }
    
    public java.lang.String getCountersignId7() {
        return this.countersignId7;
    }

    public void setCountersignId7(java.lang.String countersignId7) {
        this.countersignId7 = countersignId7;
    }
    
    public java.lang.String getCountersignId8() {
        return this.countersignId8;
    }

    public void setCountersignId8(java.lang.String countersignId8) {
        this.countersignId8 = countersignId8;
    }
    
    public java.lang.String getCountersignid1() {
        return this.countersignid1;
    }

    public void setCountersignid1(java.lang.String countersignid1) {
        this.countersignid1 = countersignid1;
    }
    
    public java.lang.String getCountersignid2() {
        return this.countersignid2;
    }

    public void setCountersignid2(java.lang.String countersignid2) {
        this.countersignid2 = countersignid2;
    }
    
    public java.lang.String getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(java.lang.String creatorId) {
        this.creatorId = creatorId;
    }
    
    public java.lang.String getCurrentStage() {
        return this.currentStage;
    }

    public void setCurrentStage(java.lang.String currentStage) {
        this.currentStage = currentStage;
    }
    
    public java.lang.String getDh() {
        return this.dh;
    }

    public void setDh(java.lang.String dh) {
        this.dh = dh;
    }
    
    public java.lang.String getDirector_01020000() {
        return this.director_01020000;
    }

    public void setDirector_01020000(java.lang.String director_01020000) {
        this.director_01020000 = director_01020000;
    }
    
    public java.lang.String getDirector_01110000() {
        return this.director_01110000;
    }

    public void setDirector_01110000(java.lang.String director_01110000) {
        this.director_01110000 = director_01110000;
    }
    
    public java.lang.String getDirector_01140000() {
        return this.director_01140000;
    }

    public void setDirector_01140000(java.lang.String director_01140000) {
        this.director_01140000 = director_01140000;
    }
    
    public java.lang.String getDirector_02010000() {
        return this.director_02010000;
    }

    public void setDirector_02010000(java.lang.String director_02010000) {
        this.director_02010000 = director_02010000;
    }
    
    public java.lang.String getErpNo() {
        return this.erpNo;
    }

    public void setErpNo(java.lang.String erpNo) {
        this.erpNo = erpNo;
    }
    
    public java.lang.String getErrorMessage() {
        return this.errorMessage;
    }

    public void setErrorMessage(java.lang.String errorMessage) {
        this.errorMessage = errorMessage;
    }
    
    public java.lang.String getFbcRoleId() {
        return this.fbcRoleId;
    }

    public void setFbcRoleId(java.lang.String fbcRoleId) {
        this.fbcRoleId = fbcRoleId;
    }
    
    public java.lang.String getFinRoleId() {
        return this.finRoleId;
    }

    public void setFinRoleId(java.lang.String finRoleId) {
        this.finRoleId = finRoleId;
    }
    
    public java.lang.String getFin_mgr() {
        return this.fin_mgr;
    }

    public void setFin_mgr(java.lang.String fin_mgr) {
        this.fin_mgr = fin_mgr;
    }
    
    public java.lang.String getFormId() {
        return this.formId;
    }

    public void setFormId(java.lang.String formId) {
        this.formId = formId;
    }
    
    public java.lang.String getFormNo() {
        return this.formNo;
    }

    public void setFormNo(java.lang.String formNo) {
        this.formNo = formNo;
    }
    
    public java.lang.String getIsAbc() {
        return this.isAbc;
    }

    public void setIsAbc(java.lang.String isAbc) {
        this.isAbc = isAbc;
    }
    
    public java.lang.String getIsSuccess() {
        return this.isSuccess;
    }

    public void setIsSuccess(java.lang.String isSuccess) {
        this.isSuccess = isSuccess;
    }
    
    public java.lang.String getLs() {
        return this.ls;
    }

    public void setLs(java.lang.String ls) {
        this.ls = ls;
    }
    
    public java.lang.String getMid() {
        return this.mid;
    }

    public void setMid(java.lang.String mid) {
        this.mid = mid;
    }
    
    public java.lang.Integer getNetValue() {
        return this.netValue;
    }

    public void setNetValue(java.lang.Integer netValue) {
        this.netValue = netValue;
    }
    
    public java.lang.String getPeRoleId() {
        return this.peRoleId;
    }

    public void setPeRoleId(java.lang.String peRoleId) {
        this.peRoleId = peRoleId;
    }
    
    public java.lang.String getPlanId() {
        return this.planId;
    }

    public void setPlanId(java.lang.String planId) {
        this.planId = planId;
    }
    
    public java.lang.String getPlanMgrId() {
        return this.planMgrId;
    }

    public void setPlanMgrId(java.lang.String planMgrId) {
        this.planMgrId = planMgrId;
    }
    
    public java.lang.String getPlanRole() {
        return this.planRole;
    }

    public void setPlanRole(java.lang.String planRole) {
        this.planRole = planRole;
    }
    
    public java.lang.String getPoRoleId() {
        return this.poRoleId;
    }

    public void setPoRoleId(java.lang.String poRoleId) {
        this.poRoleId = poRoleId;
    }
    
    public java.lang.String getPo_mgr() {
        return this.po_mgr;
    }

    public void setPo_mgr(java.lang.String po_mgr) {
        this.po_mgr = po_mgr;
    }
    
    public java.lang.String getPresident() {
        return this.president;
    }

    public void setPresident(java.lang.String president) {
        this.president = president;
    }
    
    public java.lang.Long getPrice() {
        return this.price;
    }

    public void setPrice(java.lang.Long price) {
        this.price = price;
    }
    
    public java.lang.String getProcessName() {
        return this.processName;
    }

    public void setProcessName(java.lang.String processName) {
        this.processName = processName;
    }
    
    public java.lang.String getPurchassProp() {
        return this.purchassProp;
    }

    public void setPurchassProp(java.lang.String purchassProp) {
        this.purchassProp = purchassProp;
    }
    
    public java.lang.String getReplaceId() {
        return this.replaceId;
    }

    public void setReplaceId(java.lang.String replaceId) {
        this.replaceId = replaceId;
    }
    
    public java.lang.String getResult() {
        return this.result;
    }

    public void setResult(java.lang.String result) {
        this.result = result;
    }
    
    public java.lang.String getSoureId() {
        return this.soureId;
    }

    public void setSoureId(java.lang.String soureId) {
        this.soureId = soureId;
    }
    
    public java.lang.String getStaff_pa() {
        return this.staff_pa;
    }

    public void setStaff_pa(java.lang.String staff_pa) {
        this.staff_pa = staff_pa;
    }
    
    public java.util.List<tw.org.narl.common.model.Stage> getStageList() {
        return this.stageList;
    }

    public void setStageList(java.util.List<tw.org.narl.common.model.Stage> stageList) {
        this.stageList = stageList;
    }
    
    public java.lang.String getStatus() {
        return this.status;
    }

    public void setStatus(java.lang.String status) {
        this.status = status;
    }
    
    public java.lang.String getSummary() {
        return this.summary;
    }

    public void setSummary(java.lang.String summary) {
        this.summary = summary;
    }
    
    public java.lang.Integer getTimeLimit() {
        return this.timeLimit;
    }

    public void setTimeLimit(java.lang.Integer timeLimit) {
        this.timeLimit = timeLimit;
    }
    
    public java.lang.String getVd_02010000() {
        return this.vd_02010000;
    }

    public void setVd_02010000(java.lang.String vd_02010000) {
        this.vd_02010000 = vd_02010000;
    }
    
    public java.lang.String getVdcRoleId() {
        return this.vdcRoleId;
    }

    public void setVdcRoleId(java.lang.String vdcRoleId) {
        this.vdcRoleId = vdcRoleId;
    }
    
    public java.lang.String getViceManagerId() {
        return this.viceManagerId;
    }

    public void setViceManagerId(java.lang.String viceManagerId) {
        this.viceManagerId = viceManagerId;
    }
    
    public java.lang.String getWelfare() {
        return this.welfare;
    }

    public void setWelfare(java.lang.String welfare) {
        this.welfare = welfare;
    }
}