package tw.org.narl.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(55166a46136ff0711b57a54b17b1f72c)
 */
@org.kie.api.definition.type.Label(value = "\u95DC\u5361")
public class Stage extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "\u7C3D\u6838\u4EBA")
    @org.kie.api.definition.type.Position(value = 1)
    private tw.org.narl.common.model.Approver approver;
    
    @org.kie.api.definition.type.Label(value = "\u52A0\u8A3B\u95DC\u5361")
    @org.kie.api.definition.type.Position(value = 5)
    private java.util.List<tw.org.narl.common.model.Stage> commentStage;
    
    @org.kie.api.definition.type.Label(value = "\u6703\u7C3D\u95DC\u5361")
    @org.kie.api.definition.type.Position(value = 4)
    private java.util.List<tw.org.narl.common.model.Stage> joinStage;
    
    @org.kie.api.definition.type.Label(value = "\u56DE\u7C3D\u4EBA")
    @org.kie.api.definition.type.Position(value = 3)
    private java.util.List<tw.org.narl.common.model.Stage> reapproveStage;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String stageId;
    
    @org.kie.api.definition.type.Label(value = "\u95DC\u5361\u72C0\u614B")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String status;

    public Stage() {
    }

    public Stage(java.lang.String stageId, tw.org.narl.common.model.Approver approver, java.lang.String status, java.util.List<tw.org.narl.common.model.Stage> reapproveStage, java.util.List<tw.org.narl.common.model.Stage> joinStage, java.util.List<tw.org.narl.common.model.Stage> commentStage) {
        this.stageId = stageId;
        this.approver = approver;
        this.status = status;
        this.reapproveStage = reapproveStage;
        this.joinStage = joinStage;
        this.commentStage = commentStage;
    }


    
    public tw.org.narl.common.model.Approver getApprover() {
        return this.approver;
    }

    public void setApprover(tw.org.narl.common.model.Approver approver) {
        this.approver = approver;
    }
    
    public java.util.List<tw.org.narl.common.model.Stage> getCommentStage() {
        return this.commentStage;
    }

    public void setCommentStage(java.util.List<tw.org.narl.common.model.Stage> commentStage) {
        this.commentStage = commentStage;
    }
    
    public java.util.List<tw.org.narl.common.model.Stage> getJoinStage() {
        return this.joinStage;
    }

    public void setJoinStage(java.util.List<tw.org.narl.common.model.Stage> joinStage) {
        this.joinStage = joinStage;
    }
    
    public java.util.List<tw.org.narl.common.model.Stage> getReapproveStage() {
        return this.reapproveStage;
    }

    public void setReapproveStage(java.util.List<tw.org.narl.common.model.Stage> reapproveStage) {
        this.reapproveStage = reapproveStage;
    }
    
    public java.lang.String getStageId() {
        return this.stageId;
    }

    public void setStageId(java.lang.String stageId) {
        this.stageId = stageId;
    }
    
    public java.lang.String getStatus() {
        return this.status;
    }

    public void setStatus(java.lang.String status) {
        this.status = status;
    }
}