//created on: Oct 12, 2014
package tw.org.narl.procurement.drools;

//list any import classes here.
import tw.org.narl.common.model.Stage;
import tw.org.narl.common.model.Form;
import tw.org.narl.common.model.Approver;
import com.redhat.prj.narl.api.purchase.NarlRole;

//declare any global variables here

rule "Stage3-1"
	ruleflow-group "planRole"
    when
        form : Form()
    then
		System.out.println("fire Stage3-1 分項計畫主持人!");
        Stage stage = new Stage();
        Approver approver = new Approver();
        approver.setRoleId(NarlRole.getPlanRole(form.getPlanRole()));
        
		stage.setStageId("3-1");
		stage.setApprover(approver);
		form.getStageList().add(stage);

end

rule "Stage3-2"
	ruleflow-group "planRole"
    when
        form : Form(price > 100000)
    then
		System.out.println("fire Stage3-2 總項計畫主持人!");
        Stage stage = new Stage();
        Approver approver = new Approver();
        approver.setRoleId(NarlRole.getTPlanRole(form.getPlanRole()));
        
		stage.setStageId("3-2");
		stage.setApprover(approver);
		form.getStageList().add(stage);

end

rule "Stage3-3"
	ruleflow-group "planRole"
    when
        form : Form()
    then
		System.out.println("fire Stage3-3 整合型計畫主持人!");
        Stage stage = new Stage();
        Approver approver = new Approver();
        approver.setRoleId(NarlRole.getPlanRole(form.getPlanId()));
        
		stage.setStageId("3-3");
		stage.setApprover(approver);
		form.getStageList().add(stage);

end
